import {z} from 'zod';
import {companies,investors,money,agentNames} from '@/lib/growth/data';
import {financing,scoreMatch,matchEligibility,matchFactors} from '@/lib/growth/engine.mjs';
const schema=z.object({companyId:z.string(),investorId:z.string(),question:z.string().min(1).max(2000),equity:z.number().min(0).max(5000000),debt:z.number().min(0).max(5000000)});
export async function POST(request:Request){
 let input;try{input=schema.parse(await request.json())}catch{return Response.json({error:'Choose a company and investor, and provide a valid question.'},{status:400})}
 const c=companies.find(c=>c.id===input.companyId);const i=investors.find(i=>i.id===input.investorId);if(!c||!i)return Response.json({error:'Synthetic record not found.'},{status:404});
 const f=financing(c.ask,input.debt,input.equity,c.valuation,c.cash);const sectorFit=i.sector===c.sector;const eligible=matchEligibility(c,i,input.equity);
 const factors=matchFactors(c,i,input.equity);const score=scoreMatch(factors,true);
 const results=[
  {agent:agentNames[0],summary:`${money(c.revenue)} revenue; ${money(c.ebitda)} EBITDA. Synthetic accounts loaded; cash-flow assumptions require review.`,source:'FY2025 management accounts'},
  {agent:agentNames[1],summary:`${i.source}. ${i.ticket} ticket; ${i.horizon} horizon. ${i.id==='adrian'?'Participation must be confirmed.':'Client criteria available for internal comparison.'}`,source:'Investor mandate'},
  {agent:agentNames[2],summary:`${money(input.debt)} bank debt + ${money(input.equity)} equity. ${f.dscr.toFixed(2)}× base debt coverage. ${f.gap===0?'Sources balanced.':`${money(Math.abs(f.gap))} ${f.gap>0?'shortfall':'surplus'}.`}`,source:'Growth funding schedule'},
  {agent:agentNames[3],summary:`${score}/100 alignment from seven weighted factors. ${eligible?'Ticket within mandate.':'Mandate or ticket blocks introduction.'} ${sectorFit?'Sector focus aligns.':'Sector alignment is limited.'}`,source:'Investor mandate'},
  {agent:agentNames[4],summary:`Downside coverage ${f.downsideDscr.toFixed(2)}×. Review forecasts, valuation, security and minority rights before any introduction.`,source:'Diligence checklist'},
  {agent:agentNames[5],summary:`Introduction outline: ${c.name}'s growth plan, ${i.name.split(' ')[0]}'s strategic expertise, proposed funding and material risks. Human release gate retained.`,source:'Growth funding schedule'}
 ];
 const q=input.question.toLowerCase();let answer:string;let selected:number[];
 if(/risk|cash|financial|ebitda|revenue|debt service|health/.test(q)){selected=[0,2,4];answer=`${c.name} reports ${money(c.revenue)} of synthetic FY2025 revenue and ${money(c.ebitda)} of EBITDA (${(c.ebitda/c.revenue*100).toFixed(1)}% margin).\n\nThe ${money(input.debt)} draft bank facility produces ${money(f.annualPayment)} annual new debt service. Including S$100k existing debt service, base cash coverage is ${f.dscr.toFixed(2)}× and downside coverage is ${f.downsideDscr.toFixed(2)}×. ${f.downsideDscr<1.3?'The downside falls below the illustrative 1.30× threshold; flag this for credit review.':'This exceeds the illustrative 1.30× threshold, but does not establish credit approval.'}\n\nKey diligence: validate cash forecasts, customer concentration, existing covenants and proposed security. EBITDA is not cash available for repayment.`}
 else if(/help|expertise|strategic|contribut/.test(q)){selected=[1,3,4];answer=`${i.name}'s documented experience is in ${i.expertise.toLowerCase()}. ${sectorFit?'This aligns with the company’s sector.':'This is outside the company’s primary sector focus, so the strategic case requires further discussion.'}\n\n${c.name} wants to ${c.need.charAt(0).toLowerCase()+c.need.slice(1)} A useful introduction would explore specific operating advice, partner access and a realistic advisory time commitment. These are potential contributions, not promises.\n\n${i.id==='adrian'?'Portfolio holdings suggest expertise, but participation and preferences remain unconfirmed.':'The confirmed synthetic mandate supports an internal discussion; both parties still need to agree the involvement.'}`}
 else if(/acra|registry|incorpor|profile|summari|company|business/.test(q)&&!/match|workflow/.test(q)){selected=[0,4];answer=`${c.name} is a fictitious Singapore-headquartered ${c.sector.toLowerCase()} business established in ${c.founded}. ${c.description}\n\nThe company is seeking ${money(c.ask)} for its next growth phase: ${c.need}\n\nThe synthetic FY2025 snapshot shows ${money(c.revenue)} revenue, ${money(c.ebitda)} EBITDA and ${c.growth}% revenue growth. The registry-style reference is SYN-${c.id.toUpperCase()}-001. No live ACRA verification has been performed.\n\nOpen the evidence room for the management accounts, funding schedule and outstanding diligence questions.`}
 else if(/financ|structure|equity|capital|ownership|dilution|750/.test(q)){selected=[0,2,4];answer=`The current scenario combines ${money(input.debt)} of bank debt and ${money(input.equity)} of primary equity against ${money(c.ask)} of growth funding. ${f.gap===0?'The sources balance.':`There is a ${money(Math.abs(f.gap))} ${f.gap>0?'funding shortfall':'surplus'}.`}\n\nAt the supplied ${money(c.valuation)} pre-money valuation, this equity represents ${f.ownership.toFixed(1)}% ownership. The bank loan assumes five years, 7% fixed interest and equal annual payments.\n\n${/750/.test(q)?`At S$750k equity with the bank loan unchanged, the gap would be ${money(c.ask-input.debt-750000)}. Use Capital structure to apply the scenario. `:''}Bank debt is not increased automatically. Changes require renewed credit and introduction reviews.`}
 else if(/match|why|fit|workflow|compare|alignment/.test(q)){selected=[0,1,2,3,4,5];answer=`${c.name} × ${i.name}: ${score}/100 alignment across seven weighted factors. ${sectorFit?'The strongest connection is sector experience and the company’s growth needs.':'Sector alignment is limited; the numerical fit should not be treated as a recommendation.'}\n\nThe proposed ${money(input.equity)} equity cheque ${input.equity<=i.max?'is within':'exceeds'} the stated maximum of ${money(i.max)}. The draft bank contribution is ${money(input.debt)}. ${i.id==='adrian'?'Program participation and a confirmed mandate are still missing.':`The investor's holding horizon is ${i.horizon}.`}\n\nThe score explains compatibility, not investment success. ${f.gap!==0?'The funding imbalance must be resolved. ':''}Cash-flow downside, valuation, consent and disclosure remain explicit review points. Expand the factor breakdown below to inspect the arithmetic.`}
 else {selected=[0,4];answer=`I can explain this synthetic company, the investor match, strategic expertise, financial risks, registry record or the current financing scenario. I do not have evidence to answer “${input.question}” reliably.\n\nTry “Why this match?”, “What are the financial risks?” or “Explain the capital structure”.`}
 return Response.json({mode:'guided-simulation',answer,trace:selected.map(n=>results[n]),score,eligible,financing:f},{headers:{'Cache-Control':'no-store'}});
}
