"use client";
import '@/app/immersive.css';
import {useState} from 'react';
import {ArrowUpRight,ArrowRight,ArrowLeft,Users,Building2,Network,Layers3,CalendarDays,ShieldCheck,Sparkles,ChevronRight,ArrowDown,Command,MoveUpRight,Orbit,ScanLine} from 'lucide-react';
import {World} from './World';
import {DetailWorkspace} from './Workspace';
import {investors,companies,matches,money,type Company,type Investor} from '@/lib/growth/data';
type View='welcome'|'circle'|'investor'|'opportunities'|'company'|'agents'|'pitch'|'meetings';
export default function ImmersiveApp(){
 const [view,setView]=useState<View>('welcome');const [role,setRole]=useState<'wealth'|'business'>('wealth');const [investor,setInvestor]=useState<Investor>(investors[0]);const [company,setCompany]=useState<Company>(companies[0]);const [detailTab,setDetailTab]=useState('overview');
 const go=(v:View)=>{if(v==='company')setDetailTab('overview');if(v==='agents'||v==='pitch')setDetailTab(v);setView(v);window.scrollTo({top:0,behavior:'smooth'})};
 const openCompany=(c:Company,i?:Investor)=>{setCompany(c);if(i)setInvestor(i);go('company')};
 const openInvestor=(i:Investor)=>{setInvestor(i);go('investor')};
 const menu=[{id:'circle',icon:Users,label:role==='wealth'?'Private circle':'Growth businesses'},{id:'opportunities',icon:Network,label:'Opportunities'},{id:'agents',icon:Sparkles,label:'Agent room'},{id:'pitch',icon:Layers3,label:'Pitch studio'},{id:'meetings',icon:CalendarDays,label:'Pitching day'}];
 const detail=view==='company'||view==='agents'||view==='pitch';
 const world=detail?(detailTab==='overview'?'company':detailTab):view==='circle'&&role==='business'?'business':view;
 return <div className={`immersive-suite scene-${view}`}>
  <World view={world}/>
  <header className="suite-header"><button className="suite-brand" onClick={()=>go('welcome')} aria-label="Growth Circle welcome"><span className="brand-symbol">g<span>c</span></span><span>growth circle<small>PRIVATE CAPITAL, PERSONALLY CONNECTED.</small></span></button><div className="suite-header-right"><a className="version-link" href="/classic">Version 01 <ArrowUpRight size={13}/></a><span className="suite-version">THE IMMERSIVE EDITION <span>02</span></span>{view!=='welcome'&&<button className="suite-rm" onClick={()=>{setRole(role==='wealth'?'business':'wealth');go('circle')}}><span className="rm-orb">{role==='wealth'?'SL':'JC'}</span><span>{role==='wealth'?'Sarah Lee':'James Chen'}<small>{role==='wealth'?'Private Wealth':'Emerging Business'} <ArrowUpRight size={10}/></small></span></button>}</div></header>
  <div className="suite-coordinate"><span>01°17′ N · 103°51′ E</span><i/><span>SINGAPORE</span></div>
  {view==='welcome'?<main className="suite-welcome"><div className="suite-kicker"><span className="light-dot"/> A DIFFERENT KIND OF CAPITAL CONNECTION</div><h1>Possibility.<br/><em>In good company.</em></h1><p>The ambition of emerging businesses.<br/>The experience of exceptional investors.<br/>One circle, brought together by your bank.</p><div className="suite-welcome-actions"><button className="suite-cta" onClick={()=>{setRole('wealth');go('circle')}}>Enter your private circle <span><ArrowUpRight size={21}/></span></button><button className="suite-text-link" onClick={()=>{setRole('business');go('circle')}}>Emerging Business workspace <ArrowUpRight size={16}/></button></div><div className="world-label"><span>THE GROWTH ECOSYSTEM</span><span className="world-label-rule"/><p>Capital is only the beginning.</p></div><div className="suite-welcome-bottom"><div><span>GROWTH FUNDING</span><strong>S$200k — S$5m</strong></div><div><span>COLLECTIVE INTELLIGENCE</span><strong>Six specialists. <em>One perspective.</em></strong></div><div><span>THE RELATIONSHIP</span><strong>Always bank-led.</strong></div><span className="welcome-index">EXPLORE THE CIRCLE <ArrowDown size={16}/></span></div></main>:<>
  <main className="suite-main">
   {view==='circle'&&<><section className="circle-hero"><div className="suite-kicker"><span className="tiny-rule"/>{role==='wealth'?'YOUR RELATIONSHIPS. A WORLD OF POSSIBILITY.':'AMBITION HAS FOUND ITS CIRCLE.'}</div><h1>{role==='wealth'?<>Good company.<br/><em>Extraordinary potential.</em></>:<>Built with ambition.<br/><em>Grown with experience.</em></>}</h1><p>{role==='wealth'?'Welcome back, Sarah. Four remarkable people. Their next chapter starts with a connection.':'Welcome back, James. Connect your businesses with capital—and the people who know what comes next.'}</p><div className="hero-mini-stats"><div><strong>04</strong><span>{role==='wealth'?'PRIVATE RELATIONSHIPS':'GROWTH BUSINESSES'}</span></div><i/><div><strong>{role==='wealth'?'S$5.05m':'S$11m'}</strong><span>{role==='wealth'?'EQUITY OPPORTUNITIES':'GROWTH CAPITAL SOUGHT'}</span></div><i/><button onClick={()=>go('meetings')}><strong>24 Sep <ArrowUpRight size={19}/></strong><span>YOUR NEXT PITCHING DAY</span></button></div></section>
   <section className="circle-section"><div className="suite-section-heading"><div><span className="suite-section-index">01 / {role==='wealth'?'THE PRIVATE CIRCLE':'THE GROWTH CIRCLE'}</span><h2>{role==='wealth'?'People. Purpose. Possibility.':'The next generation of growth.'}</h2></div><span className="suite-note">{role==='wealth'?'A portfolio of relationships.':'Your businesses. Their potential partners.'}</span></div>{role==='wealth'?<div className="immersive-investors">{investors.map((i,index)=><button className={`investor-vessel vessel-${i.color}`} key={i.id} onClick={()=>openInvestor(i)}><div className="vessel-topline"><span>0{index+1}</span><span className="vessel-arrow"><ArrowUpRight size={17}/></span></div><div className="vessel-world"><div className="vessel-orbit one"/><div className="vessel-orbit two"/><div className="vessel-orbit three"/><span className="vessel-monogram">{i.initials}</span><span className="vessel-point"/></div><div className="vessel-copy"><span>{i.title}</span><h3>{i.name}</h3><p>{i.sector}</p><div><strong>{i.ticket}</strong><span>{i.source==='Confirmed mandate'?'Mandate confirmed':'Portfolio inferred'}</span></div></div></button>)}</div>:<div className="immersive-businesses">{companies.map((c,index)=><Opportunity key={c.id} company={c} number={index+1} onClick={()=>openCompany(c,investors[index])}/>)}</div>}</section>
   <section className="discovery-ribbon"><span className="discovery-spark"><Sparkles size={23} strokeWidth={1}/></span><div><span className="suite-section-index">A CONNECTION WORTH EXPLORING</span><h3>Harbour Precision <em>meets</em> Evelyn Tan.</h3><p>Manufacturing ambition. An operator’s experience. 86 points of alignment.</p></div><button onClick={()=>openCompany(companies[0],investors[0])}>Explore the connection <ArrowUpRight size={20}/></button></section>
   </>}
   {view==='investor'&&<><button className="back-link" onClick={()=>go('circle')}><ArrowLeft size={15}/> The private circle</button><section className={`immersive-profile profile-${investor.color}`}><div className="profile-narrative"><div className="suite-kicker">PRIVATE RELATIONSHIP / {investor.title.toUpperCase()}</div><h1>{investor.name.split(' ')[0]}<br/><em>{investor.name.split(' ').slice(1).join(' ')}.</em></h1><p>{investor.bio}</p><span className="suite-pill"><span className="light-dot"/>{investor.source}</span></div><div className="profile-orbit"><div className="profile-orbit-ring ring-a"/><div className="profile-orbit-ring ring-b"/><div className="profile-orbit-ring ring-c"/><span className="profile-core">{investor.initials}</span><span className="profile-tag tag-one"><span>INVESTMENT TICKET</span><strong>{investor.ticket}</strong></span><span className="profile-tag tag-two"><span>INVESTMENT HORIZON</span><strong>{investor.horizon}</strong></span><span className="profile-tag tag-three"><span>STRATEGIC VALUE</span><strong>{investor.expertise}</strong></span></div></section><div className="profile-details"><section><span className="suite-section-index">01 / CAPITAL WITH INTENTION</span><h2>The mandate.</h2><dl><dt>Sector focus</dt><dd>{investor.sector}</dd><dt>Geography</dt><dd>{investor.geography}</dd><dt>Ownership</dt><dd>{investor.id==='adrian'?'To confirm':'10–20% · minority equity'}</dd><dt>Participation</dt><dd>{investor.id==='adrian'?'Confirmation required':'Confirmed synthetic mandate'}</dd></dl></section><section><span className="suite-section-index">02 / A BROADER PERSPECTIVE</span><h2>The portfolio.</h2><div className="immersive-allocation"><span style={{width:`${investor.allocation}%`}}/></div><div className="allocation-key"><strong>{investor.allocation}%</strong><span>Illustrative private-markets allocation</span></div>{investor.holdings.map(h=><div className="portfolio-holding" key={h}><span>{h.split(' · ')[0]}</span><strong>{h.split(' · ')[1]}</strong></div>)}</section></div><div className="suite-section-heading"><div><span className="suite-section-index">03 / POSSIBILITIES, PERSONALLY CURATED</span><h2>In {investor.name.split(' ')[0]}’s orbit.</h2></div><span className="suite-note">Every match has a reason.</span></div><div className="immersive-businesses">{matches(investor).map((c,index)=><Opportunity key={c.id} company={c} number={index+1} score={c.displayScore} eligible={c.eligible} onClick={()=>openCompany(c)}/>)}</div></>}
   {view==='opportunities'&&<><section className="opportunities-intro"><div className="suite-kicker"><span className="tiny-rule"/> THE NEXT CHAPTER OF BUSINESS</div><h1>Exceptional ambition.<br/><em>Meet its next horizon.</em></h1><p>Explore the businesses where capital and experience can make a difference.</p><span className="suite-pill">04 BUSINESSES <span/> S$11m IN GROWTH FUNDING</span></section><div className="immersive-businesses opportunity-collection">{companies.map((c,index)=><Opportunity key={c.id} company={c} number={index+1} onClick={()=>openCompany(c,investors[index])}/>)}</div></>}
   {detail&&<div className="immersive-detail"><DetailWorkspace key={company.id+'-'+investor.id} company={company} investor={investor} role={role} initialTab={detailTab} onTabChange={tab=>{setDetailTab(tab);setView(tab==='agents'?'agents':tab==='pitch'?'pitch':'company')}} onBack={()=>go('opportunities')}/></div>}
   {view==='meetings'&&<><section className="immersive-meeting-hero"><div><div className="suite-kicker">THE PRIVATE BANKING LOUNGE / SINGAPORE</div><h1>A meeting of minds.<br/><em>A beginning of possibilities.</em></h1><p>Four curated introductions. A shared ambition to build what comes next.</p></div><div className="meeting-date-sculpture"><span>24</span><p>SEPTEMBER<br/>THURSDAY / 2026</p></div></section><div className="suite-section-heading"><div><span className="suite-section-index">THE DAY’S CONVERSATIONS</span><h2>Make the introduction matter.</h2></div><span className="suite-note">Prepared with your agent team.</span></div><div className="immersive-meetings">{companies.map((c,index)=><article key={c.id}><div className="meeting-clock"><strong>{['10:00','10:45','11:30','14:00'][index]}</strong><span>45 MIN</span></div><div className="meeting-pair"><span className="meeting-monogram">{c.initials}</span><span className="meeting-pair-line"/><span className="meeting-monogram investor">{investors[index].initials}</span></div><div className="meeting-subject"><h3>{c.name}</h3><p>In conversation with {investors[index].name}</p><span>{investors[index].expertise}</span></div><button className="suite-circle-button" aria-label={`Prepare ${c.name} meeting`} onClick={()=>{setCompany(c);setInvestor(investors[index]);go('pitch')}}><ArrowUpRight size={22}/></button></article>)}</div><div className="meeting-status-line"><ShieldCheck size={16}/><span>Proposed introductions · all meetings remain subject to client consent and approval.</span></div></>}
   <footer className="suite-footer"><span><ShieldCheck size={14}/> BANK-LED. HUMAN-APPROVED.</span><span>Growth Circle / Immersive Edition 02</span><span>Synthetic data · guided agent simulation</span></footer>
  </main>
  <nav className="suite-dock" aria-label="Workspace navigation"><span className="dock-anchor"><Orbit size={23} strokeWidth={1}/></span>{menu.map(item=><button key={item.id} className={(view===item.id||(item.id==='circle'&&view==='investor')||(item.id==='opportunities'&&view==='company'))?'active':''} onClick={()=>go(item.id as View)} aria-label={item.label}><item.icon size={18} strokeWidth={1.5}/><span>{item.label}</span>{view===item.id&&<i/>}</button>)}<span className="dock-end"><span className="light-dot"/></span></nav>
  </>}
 </div>;
}
function Opportunity({company:c,number,score,eligible=true,onClick}:{company:Company;number:number;score?:number;eligible?:boolean;onClick:()=>void}){return <button className={`immersive-opportunity opportunity-${c.color}`} onClick={onClick}><div className="opportunity-glow"/><div className="opportunity-upper"><span className="suite-section-index">0{number} / {c.tag}</span><span className="suite-circle-button"><ArrowUpRight size={20}/></span></div><div className="opportunity-emblem"><span>{c.initials}</span><div/><i/></div><div className="opportunity-copy"><span className="opportunity-location">{c.geography}</span><h3>{c.name}</h3><p>{c.description}</p></div><div className="opportunity-foot"><div><span>GROWTH FUNDING</span><strong>{money(c.ask)}</strong></div><div><span>{score!==undefined?'MATCH ALIGNMENT':'REVENUE GROWTH'}</span><strong>{score!==undefined?`${score} / 100`:`+${c.growth}%`}</strong></div><span className="opportunity-state">{eligible?'Explore possibility':'Review required'} <ArrowRight size={13}/></span></div></button>}
