import {matchEligibility,matchFactors,scoreMatch} from './engine.mjs';
export type Investor={id:string;name:string;initials:string;title:string;sector:string;geography:string;ticket:string;min:number;max:number;horizon:string;expertise:string;source:string;allocation:number;color:string;bio:string;holdings:string[]};
export type Company={id:string;name:string;initials:string;sector:string;tag:string;geography:string;ask:number;debt:number;equity:number;revenue:number;ebitda:number;cash:number;valuation:number;growth:number;description:string;need:string;score:number;factors:number[];risk:string;founded:string;color:string};
export const investors:Investor[]=[
 {id:'evelyn',name:'Evelyn Tan',initials:'ET',title:'The industrial operator',sector:'Advanced manufacturing',geography:'Singapore · Malaysia',ticket:'S$500k–1.5m',min:500000,max:1500000,horizon:'7–10 years',expertise:'Manufacturing & regional expansion',source:'Confirmed mandate',allocation:24,color:'olive',bio:'Built and exited a regional precision-engineering group. Looking for ambitious operators where her experience can make a tangible difference.',holdings:['Industrial automation · 12%','Logistics · 8%','Healthcare · 4%']},
 {id:'marcus',name:'Marcus Lim',initials:'ML',title:'The brand builder',sector:'Consumer & lifestyle',geography:'Singapore · Southeast Asia',ticket:'S$200k–600k',min:200000,max:600000,horizon:'5–7 years',expertise:'Brand strategy & distribution',source:'Confirmed mandate',allocation:18,color:'clay',bio:'A consumer entrepreneur with a network of regional distributors. Interested in distinctive brands ready to expand beyond Singapore.',holdings:['Consumer brands · 10%','Food & beverage · 5%','Technology · 3%']},
 {id:'nadia',name:'Nadia Rahman',initials:'NR',title:'The healthcare catalyst',sector:'Healthcare services',geography:'Singapore · ASEAN',ticket:'S$1m–2m',min:1000000,max:2000000,horizon:'7–10 years',expertise:'Clinical operations & governance',source:'Confirmed mandate',allocation:21,color:'blue',bio:'Former healthcare group executive with experience scaling specialist care. Values resilient economics and strong clinical governance.',holdings:['Healthcare · 13%','Medtech · 5%','Consumer · 3%']},
 {id:'adrian',name:'Adrian Koh',initials:'AK',title:'The connected strategist',sector:'Logistics & infrastructure',geography:'Singapore · ASEAN',ticket:'Mandate to confirm',min:0,max:1000000,horizon:'To confirm',expertise:'Supply chains & market access',source:'Portfolio inferred',allocation:34,color:'violet',bio:'Regional logistics holdings suggest strong sector knowledge. Program participation and investment criteria await confirmation with the client.',holdings:['Logistics · 22%','Infrastructure · 9%','Industrials · 3%']}
];
export const companies:Company[]=[
 {id:'harbour',name:'Harbour Precision',initials:'HP',sector:'Advanced manufacturing',tag:'Precision engineering',geography:'Singapore · Malaysia',ask:2400000,debt:1200000,equity:1200000,revenue:8000000,ebitda:1100000,cash:650000,valuation:6800000,growth:18.4,description:'Precision-engineered components for the next generation of regional manufacturing.',need:'Scale an automated production line and establish a Malaysia sales presence.',score:86,factors:[100,100,60,100,70,100,70],risk:'Moderate–high',founded:'2016',color:'olive'},
 {id:'orchard',name:'Orchard Table',initials:'OT',sector:'Consumer & lifestyle',tag:'Premium food brands',geography:'Singapore · Southeast Asia',ask:600000,debt:250000,equity:350000,revenue:2800000,ebitda:420000,cash:240000,valuation:3150000,growth:24.2,description:'Singapore-born pantry essentials with a growing regional following.',need:'Expand retail distribution and strengthen working capital for new listings.',score:82,factors:[100,100,60,100,70,100,30],risk:'Moderate–high',founded:'2019',color:'clay'},
 {id:'meridian',name:'Meridian Care',initials:'MC',sector:'Healthcare services',tag:'Specialist outpatient care',geography:'Singapore · ASEAN',ask:3000000,debt:1500000,equity:1500000,revenue:10500000,ebitda:1700000,cash:850000,valuation:8500000,growth:14.7,description:'An integrated specialist-care network built around better patient access.',need:'Open two specialist centres and build a regional referral network.',score:89,factors:[100,100,60,100,100,100,70],risk:'Moderate–high',founded:'2014',color:'blue'},
 {id:'straits',name:'Straits Cold Chain',initials:'SC',sector:'Logistics & infrastructure',tag:'Temperature-controlled logistics',geography:'Singapore · ASEAN',ask:5000000,debt:3000000,equity:2000000,revenue:16000000,ebitda:2200000,cash:1300000,valuation:11000000,growth:21.3,description:'Connecting regional food and healthcare supply chains with reliable cold storage.',need:'Commission a new cold-storage facility and expand cross-border capacity.',score:71,factors:[0,100,60,100,70,100,0],risk:'High',founded:'2012',color:'violet'}
];
export const factorNames=['Ticket size','Sector alignment','Risk appetite','Geography','Investment horizon','Strategic expertise','Portfolio fit'];
export const weights=[20,15,20,10,10,15,10];
export const agentNames=['Company screening','Investor profiling','Capital structuring','Opportunity matching','Due diligence','Pitch preparation'];
export const money=(n:number)=>n>=1000000?`S$${parseFloat((n/1000000).toFixed(2))}m`:`S$${Math.round(n/1000)}k`;
export function matches(investor:Investor){return companies.map(c=>({...c,displayScore:scoreMatch(matchFactors(c,investor,c.equity),true) as number,eligible:matchEligibility(c,investor,c.equity)})).sort((a,b)=>Number(b.eligible)-Number(a.eligible)||b.displayScore-a.displayScore);}

