"use client";
import {useState, type CSSProperties} from 'react';
import {ArrowUpRight,ArrowRight,ArrowLeft,Users,Building2,Network,Layers3,CalendarDays,ShieldCheck,Sparkles,ChevronRight} from 'lucide-react';
import {Sidebar,SidebarProvider,SidebarContent,SidebarHeader,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarTrigger} from '@/components/ui/sidebar';
import {investors,companies,matches,money,type Investor,type Company} from '@/lib/growth/data';
import {DetailWorkspace} from './Workspace';
type View='home'|'relationships'|'investor'|'opportunities'|'company'|'agents'|'pitch'|'meetings';
export default function GrowthApp(){
 const [role,setRole]=useState<'wealth'|'business'>('wealth');
 const [view,setView]=useState<View>('home');
 const [investor,setInvestor]=useState<Investor>(investors[0]);
 const [company,setCompany]=useState<Company>(companies[0]);
 const enter=(nextRole:'wealth'|'business')=>{setRole(nextRole);setView('relationships');};
 const openCompany=(c:Company)=>{setCompany(c);setView('company');};
 const nav=[{id:'relationships',label:role==='wealth'?'My relationships':'My businesses',icon:role==='wealth'?Users:Building2},{id:'opportunities',label:'Opportunities',icon:Network},{id:'agents',label:'Agent room',icon:Sparkles},{id:'pitch',label:'Pitch studio',icon:Layers3},{id:'meetings',label:'Pitching day',icon:CalendarDays}];
 if(view==='home') return <main className="welcome">
  <iframe className="sylva-scene" src="/threeui/sylva.html" title="Sylva living world" tabIndex={-1} aria-hidden="true" sandbox="allow-scripts allow-same-origin"/>
  <div className="welcome-shade"/>
  <header className="welcome-nav"><a href="#" className="wordmark"><span className="brand-symbol">g<span>c</span></span> growth circle<span className="brand-divider"/><small>PRIVATE CAPITAL</small></a><span className="welcome-private"><ShieldCheck size={15}/> A private banking workspace</span><span className="edition">SINGAPORE / 2026</span></header>
  <section className="welcome-copy"><div className="eyebrow"><span className="tiny-rule"/> WHERE RELATIONSHIPS CREATE POSSIBILITY</div><h1>The next chapter.<br/><em>Grown together.</em></h1><p>Exceptional businesses. Experienced investors.<br/>A world of possibility, connected by your bank.</p><div className="welcome-actions"><button className="button cream" onClick={()=>enter('wealth')}>Private Wealth workspace <ArrowUpRight size={18}/></button><button className="button glass" onClick={()=>enter('business')}>Emerging Business <ArrowUpRight size={18}/></button></div></section>
  <div className="hero-caption"><span>01 / THE GROWTH ECOSYSTEM</span><p>Capital opens doors.<br/>Experience takes you further.</p></div>
  <section className="welcome-bottom"><div><span className="small-label">THE OPPORTUNITY</span><strong>S$200k <span>—</span> S$5m</strong><p>Growth capital for emerging businesses</p></div><div><span className="small-label">THE CONNECTION</span><strong>Capital <em>+ expertise</em></strong><p>Private investors with more to contribute</p></div><div><span className="small-label">THE INTELLIGENCE</span><strong>Six agents. <em>One circle.</em></strong><p>Every opportunity, understood and explained</p></div><span className="synthetic-tag">SYNTHETIC DEMO</span></section>
 </main>;
 return <SidebarProvider style={{'--sidebar-width':'238px'} as CSSProperties}>
  <Sidebar className="growth-sidebar"><SidebarHeader><button className="sidebar-brand" onClick={()=>setView('home')}><span className="brand-symbol">g<span>c</span></span><span>growth<br/>circle<span className="brand-sub">PRIVATE CAPITAL</span></span></button><div className="workspace-switch"><button className={role==='wealth'?'selected':''} onClick={()=>{setRole('wealth');setView('relationships')}}>Private Wealth</button><button className={role==='business'?'selected':''} onClick={()=>{setRole('business');setView('relationships')}}>Emerging Business</button></div></SidebarHeader>
  <SidebarContent><span className="sidebar-label">YOUR WORKSPACE</span><SidebarMenu>{nav.map(n=><SidebarMenuItem key={n.id}><SidebarMenuButton className="nav-item" isActive={view===n.id||(n.id==='relationships'&&view==='investor')||(n.id==='opportunities'&&view==='company')} onClick={()=>setView(n.id as View)}><n.icon size={18}/><span>{n.label}</span>{n.id==='opportunities'&&<span className="nav-count">04</span>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu><div className="sidebar-insight"><span className="orbit-icon"><Sparkles size={19}/></span><p>A little intelligence.<br/><em>A bigger perspective.</em></p><button onClick={()=>setView('agents')}>Meet your agents <ArrowUpRight size={14}/></button></div></SidebarContent>
  <SidebarFooter><div className="demo-label"><span/> Synthetic demo · guided agents</div><div className="rm-person"><span className="avatar small">{role==='wealth'?'SL':'JC'}</span><div><strong>{role==='wealth'?'Sarah Lee':'James Chen'}</strong><small>{role==='wealth'?'Private Wealth RM':'Emerging Business RM'}</small></div><button aria-label="Return to welcome" onClick={()=>setView('home')}><ArrowUpRight size={17}/></button></div></SidebarFooter></Sidebar>
  <div className="app-body"><header className="topbar"><div><SidebarTrigger className="mobile-menu"/><span>GROWTH CIRCLE</span><ChevronRight size={12}/><span>{role==='wealth'?'Private Wealth':'Emerging Business'}</span></div><div className="topbar-right"><span><ShieldCheck size={14}/> Bank-led. Human-approved.</span><span className="date-label">10 SEPTEMBER 2026</span></div></header>
  <main className="workspace-main" key={role}>
   {view==='relationships'&&<><div className="page-heading"><div><div className="eyebrow">YOUR RELATIONSHIPS. THEIR NEXT CHAPTER.</div><h1>Good morning, {role==='wealth'?'Sarah':'James'}<span className="heading-period">.</span></h1><p>{role==='wealth'?'The right capital starts with the right conversation.':'Your businesses have ambition. Let’s find their next connection.'}</p></div><button className="button subtle" onClick={()=>setView('meetings')}><CalendarDays size={16}/> Pitching day <ArrowUpRight size={15}/></button></div>
    <section className="dashboard-banner"><div className="banner-text"><div className="eyebrow">A CONNECTION WORTH EXPLORING</div><h2>{role==='wealth'?<>An operator’s experience.<br/>A business’s <em>next horizon.</em></>:<>Ambition meets<br/><em>the right experience.</em></>}</h2><p>Harbour Precision × Evelyn Tan</p><button onClick={()=>{setInvestor(investors[0]);openCompany(companies[0]);}}>Explore the opportunity <ArrowUpRight size={16}/></button></div><div className="connection-art" aria-label="Harbour Precision matched with Evelyn Tan"><div className="connection-ring r1"/><div className="connection-ring r2"/><div className="connection-ring r3"/><div className="connection-node company-node">HP<small>EMERGING BUSINESS</small></div><div className="connection-line"><span/><span/><span/></div><div className="connection-node investor-node">ET<small>PRIVATE INVESTOR</small></div><div className="connection-score"><Sparkles size={13}/> 86 / 100 alignment</div></div></section>
    <div className="metrics-row"><div><span>{role==='wealth'?'Your relationships':'Growth businesses'}</span><strong>04<small>in your circle</small></strong></div><div><span>Capital in focus</span><strong>{role==='wealth'?'S$5.1m':'S$11m'}<small>{role==='wealth'?'potential equity opportunities':'total funding sought'}</small></strong></div><div><span>Agent specialists</span><strong>06<small>working together</small></strong></div><div><span>Next pitching day</span><strong>24 Sep<small>Four curated introductions</small></strong></div></div>
    <div className="section-title"><h2>{role==='wealth'?'Your private circle':'Your growth businesses'} <span>04</span></h2><span className="small-label">{role==='wealth'?'CURATED AROUND YOUR CLIENTS':'READY FOR THEIR NEXT CHAPTER'}</span></div>
    {role==='wealth'?<div className="investor-grid">{investors.map((i,idx)=><button key={i.id} className={`investor-card ${i.color}`} onClick={()=>{setInvestor(i);setView('investor')}}><div className="card-top"><span className="card-number">0{idx+1}</span><span className="circle-link"><ArrowUpRight size={17}/></span></div><span className="portrait-letter">{i.initials}</span><div className="investor-card-info"><span className="small-label">{i.title}</span><h3>{i.name}</h3><p>{i.sector}</p><div className="card-rule"/><div className="card-bottom"><span>{i.ticket}</span><span className={`mandate-badge ${i.id==='adrian'?'inferred':''}`}>{i.id==='adrian'?'Inferred interest':'Confirmed'}</span></div></div></button>)}</div>:<div className="business-grid">{companies.map(c=><CompanyCard key={c.id} c={c} onClick={()=>{setInvestor(investors.find(i=>i.sector===c.sector)||investors[0]);openCompany(c)}}/>)}</div>}
   </>}
   {view==='investor'&&<><button className="back-link" onClick={()=>setView('relationships')}><ArrowLeft size={15}/> Your private circle</button><section className="investor-profile"><div className={`profile-monogram ${investor.color}`}>{investor.initials}<span>PRIVATE CLIENT</span></div><div><div className="eyebrow">{investor.title}</div><h1>{investor.name}</h1><p>{investor.bio}</p><span className={`mandate-badge ${investor.id==='adrian'?'inferred':''}`}>{investor.source}</span></div><div className="profile-quick"><span className="small-label">INVESTMENT TICKET</span><strong>{investor.ticket}</strong><span className="small-label">HORIZON</span><strong>{investor.horizon}</strong></div></section><div className="mandate-grid"><div className="panel"><span className="eyebrow">01 / THE MANDATE</span><h3>Capital with intention</h3><dl><dt>Sector focus</dt><dd>{investor.sector}</dd><dt>Geography</dt><dd>{investor.geography}</dd><dt>Strategic value</dt><dd>{investor.expertise}</dd><dt>Ownership preference</dt><dd>{investor.id==='adrian'?'Unconfirmed':'10–20% · minority equity'}</dd></dl></div><div className="panel"><span className="eyebrow">02 / THE EXISTING PORTFOLIO</span><h3>A broader perspective</h3><div className="portfolio-bar"><span style={{width:`${investor.allocation}%`}}/><span/></div><div className="allocation-label"><b>{investor.allocation}% private markets</b><span>Illustrative allocation</span></div>{investor.holdings.map(h=><div className="holding" key={h}><span>{h.split(' · ')[0]}</span><b>{h.split(' · ')[1]}</b></div>)}</div></div><div className="section-title"><h2>Opportunities for {investor.name.split(' ')[0]}</h2><span className="small-label">EXPLAINABLE ALIGNMENT</span></div><div className="business-grid">{matches(investor).map(c=><CompanyCard key={c.id} c={c} score={c.displayScore} eligible={c.eligible} onClick={()=>openCompany(c)}/>)}</div></>}
   {view==='opportunities'&&<><div className="page-heading"><div><div className="eyebrow">CAPITAL MEETS POSSIBILITY</div><h1>Growth opportunities<span className="heading-period">.</span></h1><p>Discover the businesses behind the numbers.</p></div><span className="outline-label">4 SYNTHETIC BUSINESSES</span></div><div className="business-grid opportunity-grid">{companies.map((c,index)=><CompanyCard key={c.id} c={c} onClick={()=>{setInvestor(investors[index]);openCompany(c)}}/>)}</div></>}
   {(view==='company'||view==='agents'||view==='pitch')&&<DetailWorkspace key={company.id+'-'+investor.id} company={company} investor={investor} initialTab={view==='agents'?'agents':view==='pitch'?'pitch':'overview'} onBack={()=>setView('opportunities')} role={role}/>}
   {view==='meetings'&&<><div className="page-heading"><div><div className="eyebrow">THE CONVERSATION STARTS HERE</div><h1>Pitching day<span className="heading-period">.</span></h1><p>24 September 2026 · The Private Banking Lounge, Singapore</p></div><span className="outline-label">4 PROPOSED INTRODUCTIONS</span></div><div className="meeting-hero"><span>24</span><div><div className="eyebrow">SEPTEMBER / THURSDAY</div><h2>Ideas. Introductions.<br/><em>What comes next.</em></h2></div><CalendarDays size={90} strokeWidth={.6}/></div><div className="meeting-list">{companies.map((c,idx)=><article key={c.id}><span className="meeting-time">{['10:00','10:45','11:30','14:00'][idx]}<small>45 MINUTES</small></span><span className={`company-avatar ${c.color}`}>{c.initials}</span><div><h3>{c.name} <span>× {investors[idx].name}</span></h3><p>{investors[idx].expertise}</p></div><span className="mandate-badge inferred">Introduction pending</span><button className="button subtle" onClick={()=>{setCompany(c);setInvestor(investors[idx]);setView('pitch')}}>Prepare meeting <ArrowUpRight size={15}/></button></article>)}</div></>}
   <footer className="workspace-footer"><span>GROWTH CIRCLE <span className="footer-rule"/> A relationship-led approach to growth.</span><span>Synthetic data · No investment execution</span></footer>
  </main></div>
 </SidebarProvider>;
}
function CompanyCard({c,onClick,score,eligible=true}:{c:Company;onClick:()=>void;score?:number;eligible?:boolean}){return <button className="company-card" onClick={onClick}><div className="company-card-head"><span className={`company-avatar ${c.color}`}>{c.initials}</span><span className="circle-link"><ArrowUpRight size={17}/></span></div><span className="small-label">{c.tag}</span><h3>{c.name}</h3><p>{c.description}</p><div className="company-card-numbers"><div><span>Growth funding</span><strong>{money(c.ask)}</strong></div><div><span>{score!==undefined?'Match alignment':'Revenue growth'}</span><strong>{score!==undefined?`${score}/100`:`+${c.growth}%`}</strong></div></div><div className="company-card-footer"><span>{c.geography}</span><span>{!eligible?'Review required':'Explore opportunity'} <ArrowRight size={13}/></span></div></button>}

